### ISSUE TITLE
 "Unsubmitted Assignments" no longer appears

### ISSUE THREAD

**Issue by schan371** [ankpat/CanvasAssignmentExtension#5]
The "Unsubmitted Assignments" section no longer appears on the following: 

* Google Chrome on an HCPSS-issued Chromebook. 
* Google Chrome on a personal Windows laptop. 
* Microsoft Edge on a personal Windows laptop. 
 
It appears the extension is not working with the new Canvas upgrade for the new 2021 school year. Thank you for your help!

**Comment by ankpat** [comment]
Thank you so much for reporting this issue. 

There was a change to the layout for the 2021 school year which caused the assignments to be placed into an invisible page element. 

V4.0 addresses this issue and builds in some resiliency to handle some additional changes made to Canvas for this school year.
